project:
  type: website
  output-dir: docs

website:
  title: "Séminaire les mesures de l'économie"
  sidebar:
    - title: "Contenu"
      style: "docked"
      contents: 
        - index.qmd
        - slides intro.qmd
        - cours2.qmd
        - cours3.qmd
format:
  html:
    theme: flatly