project:
  type: website
  output-dir: docs

website:
  title: "Séminaire les mesures de l'économie"
  sidebar:
    - title: "Slides"
      style: "docked"
      contents: 
        - index.qmd
        - slides intro.qmd
        - 3mars_cours2.qmd
        - 10mars_cours3.qmd
format:
  html:
    theme: flatly